title: MS365 Calendar for Home Assistant
remote_theme: just-the-docs/just-the-docs

search_enabled: true
search:
  heading_level: 3

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/RogerSelwyn/MS365-Calendar" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# External navigation links
nav_external_links:
  - title: General Docs
    url: https://rogerselwyn.github.io/MS365-HomeAssistant/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
