name: Python tests

on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Install Python 3.14
        run: uv python install 3.14


      - name: "Create venv"
        run: uv venv

      - name: "Install requirements"
        run: uv pip install -r requirements_test.txt

      - name: "Run pytest"
        run: uv run pytest tests -n auto

